### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by LostRager** [L4GSP1KE/Upload-Assistant#113]
Traceback (most recent call last):
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\kolt3\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\kolt3\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\kolt3\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\U-ASS\upload.py", line 480, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "C:\Users\kolt3\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\kolt3\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\U-ASS\upload.py", line 146, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
  File "C:\U-ASS\src\prep.py", line 329, in gather_prep
    meta = await self.tmdb_other_meta(meta)
  File "C:\U-ASS\src\prep.py", line 1188, in tmdb_other_meta
    external = tv.external_ids()
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\tmdbsimple\tv.py", line 181, in external_ids
    response = self._GET(path, kwargs)
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\tmdbsimple\base.py", line 110, in _GET
    return self._request('GET', path, params=params)
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\tmdbsimple\base.py", line 107, in _request
    return response.json()
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by L4GSP1KE** [comment]
tmdb api has been returning some bad responses this past week. they are aware and have implemented a fix on their end. https://www.themoviedb.org/talk/63540af956b9f7007b13ad3e
