### ISSUE TITLE
get_audio_v2 broken for at least some DTS:X uploads

### ISSUE THREAD

**Issue by milkdawg** [L4GSP1KE/Upload-Assistant#118]
To get audio channel count for DTS:X `Channel(s)_Original` is queried from mediainfo but either in this case I have or an update with mediainfo  `Channel(s)_Original` value is `Object Based` causing this to part of function to break.

```
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 485, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Upload-Assistant/upload.py", line 151, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli') 
  File "/Upload-Assistant/src/prep.py", line 346, in gather_prep
    meta['audio'], meta['channels'], meta['has_commentary'] = self.get_audio_v2(mi, meta, bdinfo)
  File "/Upload-Assistant/src/prep.py", line 1563, in get_audio_v2
    chan = f"{int(channels) - 1}.1"
ValueError: invalid literal for int() with base 10: 'Object Based'
```
`channels = mi['media']['track'][track_num].get('Channels_Original', mi['media']['track'][track_num]['Channels'])`
```
Audio #1
ID                                       : 2
Format                                   : DTS XLL X
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 1 h 50 min
Bit rate mode                            : Variable
Bit rate                                 : 5 650 kb/s
Channel(s)                               : 8 channels
Channel(s)_Original                      : Object Based
ChannelLayout_Original                   : Object Based
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Stream size                              : 4.36 GiB (7%)
Title                                    : DTS-X 7.1 Remix
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/9fc77ffcfec8c5aaed4a74ae4eeb89ae95e306f7

**Comment by milkdawg** [comment]
773696c ;)
