### ISSUE TITLE
Facing issue after "Adding and Starting torrent"

### ISSUE THREAD

**Issue by leonard4546** [L4GSP1KE/Upload-Assistant#12]
Creating fast resume
Adding and starting torrent
Traceback (most recent call last):
  File "upload.py", line 245, in <module>
    loop.run_until_complete(do_the_thing(path, args, base_dir))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "upload.py", line 156, in do_the_thing
    await client.add_to_client(meta, "BHD")
  File "/home/user/Upload-Assistant/src/clients.py", line 47, in add_to_client
    self.rtorrent(meta['path'], torrent_path, torrent, meta, local_path, remote_path, client)
  File "/home/user/Upload-Assistant/src/clients.py", line 109, in rtorrent
    rtorrent.load.start_verbose('', fr_file, f"d.directory_base.set={path}")
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)

I'm facing this issue. Torrent gets uploaded successfully on tracker but after that it's not adding automatically in client. I'm using rtorrent.

**Comment by L4GSP1KE** [comment]
@leonard4546 I'm unable to reproduce this so would you mind sending me what you're using for `rtorrent_url` in your config as well as your provider/setup? Obviously don't share your username/pasword/api keys. And feel free to dm me on bhd if you wish to keep this more private.
