### ISSUE TITLE
JSONDecodeError when getting MyAnimeList info

### ISSUE THREAD

**Issue by DemonicSavage** [L4GSP1KE/Upload-Assistant#120]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/twilight/Upload-Assistant/upload.py", line 485, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/twilight/Upload-Assistant/upload.py", line 151, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli') 
  File "/home/twilight/Upload-Assistant/src/prep.py", line 329, in gather_prep
    meta = await self.tmdb_other_meta(meta)
  File "/home/twilight/Upload-Assistant/src/prep.py", line 1220, in tmdb_other_meta
    meta['mal_id'], meta['aka'], meta['anime'] = self.get_anime(response, meta)
  File "/home/twilight/Upload-Assistant/src/prep.py", line 1287, in get_anime
    romaji, mal_id, eng_title, season_year, episodes = self.get_romaji(tmdb_name, meta.get('mal', None))
  File "/home/twilight/Upload-Assistant/src/prep.py", line 1356, in get_romaji
    json = response.json()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/caeb25cce0bf9f36343728d01d32f8ae8b5d58cb
