### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by khachapu** [L4GSP1KE/Upload-Assistant#123]
Every now and then, after the script scans a blu-ray disc, I get this error:
```
                File           Elapsed      Remaining
Scanning 100% - 00158.M2TS     00:02:32  |  00:00:00
Scan completed successfully.
Please wait while we generate the report...
Traceback (most recent call last):
  File "/home/user01/scripts/Upload-Assistant/upload.py", line 485, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user01/scripts/Upload-Assistant/upload.py", line 151, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
  File "/home/user01/scripts/Upload-Assistant/src/prep.py", line 92, in gather_prep
    meta['is_disc'], videoloc, bdinfo, meta['discs'] = await self.get_disc(meta)
  File "/home/user01/scripts/Upload-Assistant/src/prep.py", line 429, in get_disc
    discs, bdinfo = await parse.get_bdinfo(discs, meta['uuid'], meta['base_dir'], meta.get('discs', []))
  File "/home/user01/scripts/Upload-Assistant/src/discparse.py", line 92, in get_bdinfo
    bdinfo = self.parse_bdinfo(bd_summary, files[1], path)
  File "/home/user01/scripts/Upload-Assistant/src/discparse.py", line 175, in parse_bdinfo
    'bit_depth' : split2[n+5].strip(),
IndexError: list index out of range

```

Any ideas on how to fix it?

**Comment by L4GSP1KE** [comment]
Need more info.
Please send bdinfo report

**Comment by khachapu** [comment]
[BD_SUMMARY_00.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/10147853/BD_SUMMARY_00.txt)
[BD_SUMMARY_EXT.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/10147854/BD_SUMMARY_EXT.txt)
[BD_FULL_00.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/10147855/BD_FULL_00.txt)

```
user01@140746:~/scripts/Upload-Assistant$ python3 upload.py /home/user01/torrents/qbittorrent/movies/Madagascar.Escape.2.Africa.2008.MULTi.COMPLETE.BLURAY.iNTERNAL-LiEFERDiENST/
Gathering info for Madagascar.Escape.2.Africa.2008.MULTi.COMPLETE.BLURAY.iNTERNAL-LiEFERDiENST
Traceback (most recent call last):
  File "/home/user01/scripts/Upload-Assistant/upload.py", line 485, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user01/scripts/Upload-Assistant/upload.py", line 151, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
  File "/home/user01/scripts/Upload-Assistant/src/prep.py", line 92, in gather_prep
    meta['is_disc'], videoloc, bdinfo, meta['discs'] = await self.get_disc(meta)
  File "/home/user01/scripts/Upload-Assistant/src/prep.py", line 429, in get_disc
    discs, bdinfo = await parse.get_bdinfo(discs, meta['uuid'], meta['base_dir'], meta.get('discs', []))
  File "/home/user01/scripts/Upload-Assistant/src/discparse.py", line 92, in get_bdinfo
    bdinfo = self.parse_bdinfo(bd_summary, files[1], path)
  File "/home/user01/scripts/Upload-Assistant/src/discparse.py", line 175, in parse_bdinfo
    'bit_depth' : split2[n+5].strip(),
IndexError: list index out of range
```

**Comment by L4GSP1KE** [comment]
Thanks <3
Should be fixed in https://github.com/L4GSP1KE/Upload-Assistant/commit/34ff8545a04ef1a6a70295963f4921b959ce0280

Also unrelated to the error, that is a 3D disc which should stay in .iso, and the script does not support .isos :)
