### ISSUE TITLE
HDB title renaming failing

### ISSUE THREAD

**Issue by milkdawg** [L4GSP1KE/Upload-Assistant#125]
Filename: South.Park.S00E01.Cartman.Gets.an.Anal.Probe.The.Unaired.and.Uncut.Original.Pilot.NTSC.DVD.REMUX.DD.2.0-MiLKnCOOKiES.mkv

```
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 490, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Upload-Assistant/upload.py", line 258, in do_the_thing
    await tracker_class.upload(meta)
  File "/Upload-Assistant/src/trackers/HDB.py", line 206, in upload
    hdb_name = await self.edit_name(meta)
  File "/Upload-Assistant/src/trackers/HDB.py", line 181, in edit_name
    hdb_name = hdb_name.replace(meta['audio', meta['audio'].replace('Atmos', '')])
KeyError: ('audio', 'DD 2.0')
```

**Comment by L4GSP1KE** [comment]
Is it an error. Yes. 
Is it something worth fixing. No.
