### ISSUE TITLE
requests.exceptions.HTTPError

### ISSUE THREAD

**Issue by khachapu** [L4GSP1KE/Upload-Assistant#126]
Hi,

The upload assistant freaks out after it can't find the TMDB ID automatically and I enter it manually. Please see below.
Things that I checked:
1. The problem doesn't seem to be on the TMDB side of things, as other releases get TMDB info just fine (I tried other releases before I got this error, and after).
2. This is the only release that got this problem so far, so I'm not sure if there's anything special about it or it's just a particular case that hasn't been implemented.

```
Scanning 100% - 00005.M2TS     00:02:36  |  00:00:00
Scan completed successfully.
Please wait while we generate the report...
Saving Screens...
Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 0:00:00
Unable to find TMDb match for MOONSTALKER VS
:: Please enter tmdb id:
> 85176
Traceback (most recent call last):
  File "/home/user01/scripts/Upload-Assistant/upload.py", line 485, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user01/scripts/Upload-Assistant/upload.py", line 151, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
  File "/home/user01/scripts/Upload-Assistant/src/prep.py", line 329, in gather_prep
    meta = await self.tmdb_other_meta(meta)
  File "/home/user01/scripts/Upload-Assistant/src/prep.py", line 1181, in tmdb_other_meta
    response = tv.info()
  File "/home/user01/.local/lib/python3.9/site-packages/tmdbsimple/tv.py", line 71, in info
    response = self._GET(path, kwargs)
  File "/home/user01/.local/lib/python3.9/site-packages/tmdbsimple/base.py", line 110, in _GET
    return self._request('GET', path, params=params)
  File "/home/user01/.local/lib/python3.9/site-packages/tmdbsimple/base.py", line 105, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/tv/85176?api_key=[EDITED]
user01@140746:~/torrents/qbittorrent/movies$
```

[BD_SUMMARY_00.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/10185895/BD_SUMMARY_00.txt)
[BD_SUMMARY_EXT.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/10185896/BD_SUMMARY_EXT.txt)
[BD_FULL_00.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/10185897/BD_FULL_00.txt)

**Comment by L4GSP1KE** [comment]
yes that is something i need to fix, but if you use the full tmdb id like movie/12345 it should work no problem
