### ISSUE TITLE
local variable 'name' referenced before assignment

### ISSUE THREAD

**Issue by khachapu** [L4GSP1KE/Upload-Assistant#132]
There's a weird issue when uploading a certain release. Please see below:
```
user01@140746:~/torrents/qbittorrent/movies/Ludwig 1973 2160p Remux DoVi HDR10 HEVC FLAC 2.0-VHS$ upload Ludwig\ 1973\ 2160p\ Remux\ DoVi\ HDR10\ HEVC\ FLAC\ 2.0-VHS.mkv
Gathering info for Ludwig 1973 2160p Remux DoVi HDR10 HEVC FLAC 2.0-VHS.mkv
Reusing screenshots
Traceback (most recent call last):
  File "/home/user01/scripts/Upload-Assistant/upload.py", line 485, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user01/scripts/Upload-Assistant/upload.py", line 152, in do_the_thing
    meta['name_notag'], meta['name'], meta['clean_name'], meta['potential_missing'] = await prep.get_name(meta)
  File "/home/user01/scripts/Upload-Assistant/src/prep.py", line 2265, in get_name
    name = ' '.join(name.split())
UnboundLocalError: local variable 'name' referenced before assignment
user01@140746:~/torrents/qbittorrent/movies/Ludwig 1973 2160p Remux DoVi HDR10 HEVC FLAC 2.0-VHS$ 
```
[DESCRIPTION.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/10253119/DESCRIPTION.txt)
[MEDIAINFO.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/10253120/MEDIAINFO.txt)
[MEDIAINFO_CLEANPATH.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/10253121/MEDIAINFO_CLEANPATH.txt)

**Comment by L4GSP1KE** [comment]
That filename just breaks my parsers in all different ways. Added source arg and better error message so this and any similar issues can be fixed manually
