### ISSUE TITLE
New Tracker Request

### ISSUE THREAD

**Issue by DevilStyle** [L4GSP1KE/Upload-Assistant#201]
Hi, I would like to ask you if you could add support to this tracker: 

https://itatorrents.xyz/

Thanks

**Comment by swannie-eire** [comment]
this looks to be a united site from the login page so you can use the united template to make it support the site.

**Comment by Ridente** [comment]
Hello @swannie-eire 

I created a new class from united template
`
class ITT():
    """
    Edit for Tracker:
        Edit BASE.torrent with announce and source
        Check for duplicates
        Set type/category IDs
        Upload
    """

    ###############################################################
    ########                    EDIT ME                    ########
    ###############################################################

    # ALSO EDIT CLASS NAME ABOVE

    def __init__(self, config):
        self.config = config
        self.tracker = 'ITT'
        self.source_flag = 'ITT'
        self.upload_url = 'https://itatorrent.xyz/api/torrents/upload'
        self.search_url = 'https://itatorrent.xyz/api/torrents/filter'
        self.signature = None
        self.banned_groups = [""]
        pass
    
    async def get_cat_id(self, category_name):
        category_id = {
            'MOVIE': '1', 
            'TV': '2', 
            }.get(category_name, '0')
        return category_id

    async def get_type_id(self, type):
        type_id = {
            'DISC': '1', 
            'REMUX': '2',
            'WEBDL': '4', 
            'WEBRIP': '5', 
            'HDTV': '6',
            'ENCODE': '3'
            }.get(type, '0')
        return type_id

    async def get_res_id(self, resolution):
        resolution_id = {
            '8640p':'10', 
            '4320p': '1', 
            '2160p': '2', 
            '1440p' : '3',
            '1080p': '3',
            '1080i':'4', 
            '720p': '5',  
            '576p': '6', 
            '576i': '7',
            '480p': '8', 
            '480i': '9'
            }.get(resolution, '10')
        return resolution_id

    ###############################################################
    ######   STOP HERE UNLESS EXTRA MODIFICATION IS NEEDED   ######
    ###############################################################

`
Named it like 'ITT'  (itatorrents)

I updated the file update.py  like below:

+ from src.trackers.ITT import ITT

Update list and dictionary
`
api_trackers = ['BLU', 'AITHER', 'STC', 'R4E', 'STT', 'RF', 'ACM','LCD','LST','HUNO', 'SN', 'LT', 'NBL', 'ANT', 'JPTV', 'TDC']
        http_trackers = ['HDB', 'TTG', 'FL', 'PTER', 'HDT', 'MTV','ITT']
        tracker_class_map = {
            'BLU' : BLU, 'BHD': BHD, 'AITHER' : AITHER, 'STC' : STC, 'R4E' : R4E, 'THR' : THR, 'STT' : STT, 'HP' : HP, 'PTP' : PTP, 'RF' : RF, 'SN' : SN, 
            'ACM' : ACM, 'HDB' : HDB, 'LCD': LCD, 'TTG' : TTG, 'LST' : LST, 'HUNO': HUNO, 'FL' : FL, 'LT' : LT, 'NBL' : NBL, 'ANT' : ANT, 'PTER': PTER, 'JPTV' : JPTV,
            'TL' : TL, 'TDC' : TDC, 'HDT' : HDT, 'MTV': MTV, 'ITT': ITT,
            }
`

`
:: Upload to ITT?  (y/N)
> y
Uploading to ITT
Traceback (most recent call last):
  File "/home/rid/upassistant/Upload-Assistant/./upload_itt.py", line 568, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/rid/upassistant/Upload-Assistant/./upload_itt.py", line 293, in do_the_thing
    if await tracker_class.validate_credentials(meta) == True:
AttributeError: 'ITT' object has no attribute 'validate_credentials'
`
What's the next step ?
Can you help me, or else I have to study the entire code
Thank you

**Comment by L4GSP1KE** [comment]
place ITT in the api_trackers instead of http_trackers

**Comment by Ridente** [comment]
Hello Thank you for responding. But i've another error:

`
Uploading to ITT                                                                                                       
Searching for existing torrents on site...
Unable to search for existing torrents on site. Either the site is down or your API key is incorrect
`

`
from ITT.py
....
  self.upload_url = 'https://itatorrent.xyz/api/torrents/upload'
  self.search_url = 'https://itatorrent.xyz/api/torrents/filter'
....
`


`
from config.py
....
  "TRACKERS": {
        # Which trackers do you want to upload to?
        "default_trackers": "ITT,BLU, BHD, AITHER, STC, STT, SN, THR, R4E, HP, ACM, PTP, LCD, LST, PTER, NBL, ANT, MTV",

        "ITT": {
            "useAPI": True,  # Set to True  ITT
            "api_key": "xxxxxxxxxxxxxxxxxxxx..",  # API TOKEN from "My Security menù"
            "announce_url": "https://itatorrent.xyz/announce/xxxxx.." # PassKey(PID)  from "My Security menù"
            # "anon" : False
        },
        "BLU": { ....
`
I have checked, the API key is correct. What could I have forgotten ?

**Comment by Ridente** [comment]
I have set up upload-assistant on a Linux VPS, and I need to configure a new tracker along with Transmission as the torrent client

**./upload.py Oppenheimer.mkv --client transmission**

`

config = {
    "DEFAULT": {

        # ------ READ THIS ------
        # Any lines starting with the # symbol are commented and will not be used.
        # If you change any of these options, remove the #
        # -----------------------

        "tmdb_api": "xxxxxxxx",
        "imgbb_api": "imgbb api key",
        "ptpimg_api": "ptpimg api key",
        "lensdump_api": "lensdump api key",

        # Order of image hosts, and backup image hosts
        "img_host_1": "imgbb",
        "img_host_2": "ptpimg",
        "img_host_3": "imgbox",
        "img_host_4": "pixhost",
        "img_host_5": "lensdump",

        "screens": "6",
        # Enable lossless PNG Compression (True/False)
        "optimize_images": True,

        # The name of your default torrent client, set in the torrent client sections below
        "default_torrent_client": "transmission",

        # Play the bell sound effect when asking for confirmation
        "sfx_on_prompt": True,

    },

    "TRACKERS": {
        # Which trackers do you want to upload to?
        "default_trackers": "ITT",

        "ITT": {
            "useAPI": True,  # Set to True  ITT
            "api_key": "api key from my security menù",
            "announce_url": "https://xxxx/announce/passkey(pid) from my security menù",
            # "anon" : False
        },

    },

    "TORRENT_CLIENTS": {
        # Name your torrent clients here, for example, this example is named "Client1"
        "transmission": {
            "torrent_client": "transmission-cli",
            "transmission-cli_url": "http://127.0.0.1",
            "transmission-cli_port": "9091",
            "transmission-cli_user": "transmission",
            "transmission-cli_pass": "transmission",
        },
    },
}


`

`
Uploading to ITT
Searching for existing torrents on site...
Unable to search for existing torrents on site. Either the site is down or your API key is incorrect
`
Does the error message refer to TMDB?




https://github.com/L4GSP1KE/Upload-Assistant/wiki/Configuration#torrent-clients
`
This field is REQUIRED and only ONE is needed, but if you have more, you can switch easily by changing the default_torrent_client or calling --client [NAME] while uploading.
`
I declared default_torrent_client  like  "default_torrent_client": "transmission",

1) But without the --client flag, the uploader keeps searching for qbit.
2) by --client flag it retturns : KeyError: 'transmission'


 # "transmission-cli_url": "http://transmission:transmission@127.0.0.1:9091/transmission/rpc",

**Comment by Ridente** [comment]
Thank you works. One question: When the video is already present in the tracker, why do you ask if I still want to proceed with the upload? If I choose 'yes,' I still receive a hash error
