### ISSUE TITLE
Docker not starting. Cant find config

### ISSUE THREAD

**Issue by LargeTalons** [L4GSP1KE/Upload-Assistant#236]
I am getting the following error

```
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 58, in <module>
    from data.config import config
  File "/Upload-Assistant/data/config.py", line 288
    }
    ^
SyntaxError: unmatched '}'
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 83, in <module>
    client = Clients(config=config)
                            ^^^^^^
NameError: name 'config' is not defined
None
```

These are my mappings:

```
  -v '/mnt/user/appdata/Upload-Assistant/config.py':'/Upload-Assistant/data/config.py'
  -v '/mnt/user/appdata/qbittorrent-vpn/data/BT_backup/':'/BT_backup'
  -v '/mnt/user/media/torrents/':'/downloads'
```
For whatever reason, the docker refuses to see my config.py file. I copied the sample from the repo, renamed it to "config.py" and made the appropriate changes.

Any advice? I'm not sure where to proceed from here. Ive tried moving the file to a folder and referencing it there. Ive also tried letting the container create the file, but it creates it as a folder instead of a .py file. Perhaps, this is what the issue is. I dont know how to correct the behavior, though.

**Comment by LargeTalons** [comment]
Nevermind. I decided to run it on my windows machine just to test and ran into the same issue. There were some lines of code that had errors that I needed to resolve.
