### ISSUE TITLE
Bug: CleanUp Path Validation

### ISSUE THREAD

**Issue by karserasl** [L4GSP1KE/Upload-Assistant#251]
Need some path validation on cleanup command

```bash
❯ python3 upload.py -cleanup
Sucessfully emptied tmp directory
Traceback (most recent call last):
  File "/home/l***/Upload-Assistant/upload.py", line 568, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/l***/Upload-Assistant/upload.py", line 101, in do_the_thing
    path = os.path.abspath(path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 399, in abspath
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by sirius-sama** [comment]
It worked tho, and cleaned the ``tmp/`` directory.

Script expecting to execute code after this cleanup logic. That's where it's messing up. It's been there for a long time.

Passing an ``exit(1)`` after cleanup logic would work IMO.
Fixes will be there in the next update.
