### ISSUE TITLE
Name "config" not defined

### ISSUE THREAD

**Issue by jonasprokopf** [L4GSP1KE/Upload-Assistant#275]
Hello, trying to run this script on my Windows machine (after having satisfied all the requirements), throws this error.
`Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32`

```
C:\Users\\tools\Upload-Assistant-master\Upload-Assistant-master>python upload.py --help
Traceback (most recent call last):
  File "C:\Users\\tools\Upload-Assistant-master\Upload-Assistant-master\upload.py", line 60, in <module>
    from data.config import config
  File "C:\Users\\tools\Upload-Assistant-master\Upload-Assistant-master\data\config.py", line 266
    },
    ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX escape
None
Traceback (most recent call last):
  File "C:\Users\\tools\Upload-Assistant-master\Upload-Assistant-master\upload.py", line 85, in <module>
    client = Clients(config=config)
                            ^^^^^^
NameError: name 'config' is not defined

C:\Users\\tools\Upload-Assistant-master\Upload-Assistant-master>
```

**Comment by sirius-sama** [comment]
Seems like you removed a , or } from ``config.py``
A simple solution would be just to copy the ``example-config.py`` and rename it to ``config.py`` the re re-enter all the values.
Don't remove any , or } from any line, and it'll work.
