### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by RyuDragoon** [L4GSP1KE/Upload-Assistant#281]
Please let me know if you need anymore information.

```
ryu@Plex-Server:~/Upload-Assistant$ python3 upload.py /media/Storage9/Movies/The.Last.Queen.2022.1080p.BluRay.DDP5.1.x264-PTer.mkv
Gathering info for The.Last.Queen.2022.1080p.BluRay.DDP5.1.x264-PTer.mkv
SRRDB: No match found, or request has timed out
Exporting MediaInfo...
MediaInfo Exported.
Traceback (most recent call last):
  File "/home/ryu/Upload-Assistant/upload.py", line 569, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ryu/Upload-Assistant/upload.py", line 187, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
  File "/home/ryu/Upload-Assistant/src/prep.py", line 181, in gather_prep
    meta['resolution'] = self.get_resolution(guessit(video), meta['uuid'], base_dir)
  File "/home/ryu/Upload-Assistant/src/prep.py", line 520, in get_resolution
    framerate = mi['media']['track'][1].get('FrameRate', '')
IndexError: list index out of range
```

**Comment by RyuDragoon** [comment]
I have no idea what happened, but it just works now.
