### ISSUE TITLE
Deprecated distutils module as of Python 3.12

### ISSUE THREAD

**Issue by BovBrew** [L4GSP1KE/Upload-Assistant#290]
distutils module has been deprecated as of Python 3.12

found in \src\trackers\PTP.py but could be elsewhere in code.

```
import distutils.util
# Rest of the code...
        self.web_source = distutils.util.strtobool(str(config['TRACKERS']['PTP'].get('add_web_source_to_desc', True)))
```

This can be replaced with:

```
from str2bool import str2bool
# Rest of the code...
        self.web_source = str2bool(config['TRACKERS']['PTP'].get('add_web_source_to_desc', True))
```

pip install str2bool would be required or added to requirments.txt

**Comment by sirius-sama** [comment]
Are you getting any errors for ``guessit`` on v3.12.0?

```
$ python upload.py -h
Traceback (most recent call last):
  File "/home/user/bin/upload-assistant/src/prep.py", line 21, in <module>
    from guessit import guessit
  File "/home/user/bin/upload-assistant/.venv/lib/python3.12/site-packages/guessit/__init__.py", line 8, in <module>
    from .api import guessit, GuessItApi
  File "/home/user/bin/upload-assistant/.venv/lib/python3.12/site-packages/guessit/api.py", line 17, in <module>
    from .rules import rebulk_builder
  File "/home/user/bin/upload-assistant/.venv/lib/python3.12/site-packages/guessit/rules/__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "/home/user/bin/upload-assistant/.venv/lib/python3.12/site-packages/guessit/rules/properties/episodes.py", line 16, in <module>
    from .title import TitleFromPosition
  File "/home/user/bin/upload-assistant/.venv/lib/python3.12/site-packages/guessit/rules/properties/title.py", line 11, in <module>
    from .language import (
  File "/home/user/bin/upload-assistant/.venv/lib/python3.12/site-packages/guessit/rules/properties/language.py", line 10, in <module>
    import babelfish
  File "/home/user/bin/upload-assistant/.venv/lib/python3.12/site-packages/babelfish/__init__.py", line 14, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/home/user/bin/upload-assistant/.venv/lib/python3.12/site-packages/babelfish/converters/__init__.py", line 5, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
ModuleNotFoundError: No module named 'pkg_resources'
None
Missing Module Found. Please reinstall required dependancies.
pip3 install --user -U -r requirements.txt```
