### ISSUE TITLE
Feature Request - Series packs with directory/folder per season

### ISSUE THREAD

**Issue by swannie-eire** [L4GSP1KE/Upload-Assistant#33]
Currently if you try to create a torrent from a series pack you get the error below. This seems to be due to that only the root dir/folder are checked for files.

```
python3 upload.py Test.S01-S03.COMPLETE.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup
Gathering info for Test.S01-S03.COMPLETE.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroupy

Traceback (most recent call last):
  File "upload.py", line 416, in <module>
    asyncio.run(do_the_thing(path, args, base_dir))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "upload.py", line 100, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
  File "/Upload-Assistant/src/prep.py", line 171, in gather_prep
    videopath, meta['filelist'] = self.get_video(videoloc)
  File "/Upload-Assistant/src/prep.py", line 343, in get_video
    video = sorted(filelist)[0]
IndexError: list index out of range
```

I would be good if no video files were found in the root folder that the it checks the first directory and if no videos found it checks the next and so on until it finds a directory.

Here is what the dir/folder structure looks like in a typical Series pack.
```
ls Test.S01-S03.COMPLETE.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup/*
Test.S01-S03.COMPLETE.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup/Test.S01.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup:
Test.S01E01.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup.mkv
Test.S01E02.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup.mkv
Test.S01E03.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup.mkv
Test.S01E0n.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup.mkv

Test.S01-S03.COMPLETE.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup/Test.S02.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup:
Test.S02E01.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup.mkv
Test.S02E02.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup.mkv
Test.S02E03.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup.mkv
Test.S02E0n.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup.mkv

Test.S01-S03.COMPLETE.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup/Test.S0n.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup:
Test.S0nE0n.1080p.NF.WEB-DL.DD+.2.0.H264-TestGroup.mkv
```

**Comment by L4GSP1KE** [comment]
Complete season packs are not supported for non-disc content. Complete packs are bad anyways so I have no plans to support them

**Comment by swannie-eire** [comment]
Complete season packs are supported on a number of the sites your script supports e.g aither.

Not sure why you think they are bad but chances are if someone is going to be downloading a season they more than likely will be downloading all of them which makes series packs great as it means they only have to DL one torrent instead of one for every season.

**Comment by swannie-eire** [comment]
closing as i no longer need
