### ISSUE TITLE
IndexError: list index out of range...FrameRate

### ISSUE THREAD

**Issue by Zenya393** [L4GSP1KE/Upload-Assistant#348]
```
Gathering info for sh
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 575, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Upload-Assistant/upload.py", line 191, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli') 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 181, in gather_prep
    meta['resolution'] = self.get_resolution(guessit(video), meta['uuid'], base_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 520, in get_resolution
    framerate = mi['media']['track'][1].get('FrameRate', '')
                ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by mesoller** [comment]
I usually got this error due to the media itself is corrupted / unplayable

**Comment by Zenya393** [comment]
Since I am running this in batch mode on a folder with many, is it possible for:

1. The log to tell me which media has the problem.
2. Skip media with the problem.

Thank you.
