### ISSUE TITLE
Crash when detecting audio channels

### ISSUE THREAD

**Issue by argonan0** [L4GSP1KE/Upload-Assistant#49]
```
Traceback (most recent call last):
  File "upload.py", line 359, in <module>
    asyncio.run(do_the_thing(path, args, base_dir))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "upload.py", line 101, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli') 
  File "/src/prep.py", line 252, in gather_prep
    meta['audio'], meta['channels'] = self.get_audio_v2(mi, meta, bdinfo)
  File "/src/prep.py", line 1161, in get_audio_v2
    channels = mi['media']['track'][track_num]['Channels']
KeyError: 'Channels'
```

MediaInfo for file: https://pastebin.com/6by3hEcW

**Comment by L4GSP1KE** [comment]
this was fixed a few days ago (https://github.com/L4GSP1KE/Upload-Assistant/commit/f0121a132c4377bfc6290a17e67462cbe867818a)
