### ISSUE TITLE
Piece size too large for very small files. 

### ISSUE THREAD

**Issue by Skamba** [L4GSP1KE/Upload-Assistant#66]
I have some 576p Looney Tunes encodes that are about ~100 mb each. Because the torrent creation does not go under a piece size of 2^19, this ends up being too large for PTP.

```
Traceback (most recent call last):
  File "/home/xxx/uploadassistant/Upload-Assistant/./upload.py", line 333, in do_the_thing
    await ptp.upload(meta, ptpUrl, ptpData)
  File "/home/xxx/uploadassistant/Upload-Assistant/src/trackers/PTP.py", line 770, in upload
    raise UploadException(f"Upload to PTP failed: {errorMessage} ({response.status_code}). (We are still on the upload page.)")
src.exceptions.UploadException: Upload to PTP failed: <div>The piece size of 512 KiB (2^19 ~169 pieces) is not within limits. It must be 32 KiB (2^15 ~2695 pieces) to 256 KiB (2^18 ~337 pieces)<br />You can view the piece size chart here: <a href='upload.php?action=piecesize'>Piece Size Chart</a> (200). (We are still on the upload page.)
```

**Comment by L4GSP1KE** [comment]
Update to now use 2^18 for any files smaller than 256MiB
