### ISSUE TITLE
IMDbParserError ('invalid title: """"',)

### ISSUE THREAD

**Issue by LostRager** [L4GSP1KE/Upload-Assistant#68]
Happend to all 4 seasons i tried, only one thats been a problem, uploaded a bunch that had no issues. Any clues?

Tried using the args with filled in imdb and tmdb to make it skip the search, but no luck.

PS D:\kolt3\Desktop\test\Upload-Assistant> python upload.py "\\10.0.0.141\disk8\plex\TV\13.Reasons.Why.S01.2160p.NF.WEB-Gathering info for 13.Reasons.Why.S01.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1-ABBiE[rartv]
Exporting MediaInfo...
MediaInfo Exported.
Saving Screens... ---------------------------------------- 7/7 0:00:00
2022-07-25 07:20:46,916 CRITICAL [imdbpy] C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\_exceptions.py:32: IMDbParserError exception raised; args: ('invalid title: """"',); kwds: {}
NoneType: None
Traceback (most recent call last):
  File "D:\kolt3\Desktop\test\Upload-Assistant\upload.py", line 475, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "C:\Users\kolt3\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\kolt3\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\kolt3\Desktop\test\Upload-Assistant\upload.py", line 141, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
  File "D:\kolt3\Desktop\test\Upload-Assistant\src\prep.py", line 307, in gather_prep
    meta['imdb_id'] = await self.search_imdb(filename, meta['search_year'])
  File "D:\kolt3\Desktop\test\Upload-Assistant\src\prep.py", line 2768, in search_imdb
    search = ia.search_movie(f"{filename}")
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\__init__.py", line 444, in search_movie
    res = self._search_movie(title, results)
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\parser\http\__init__.py", line 409, in _search_movie
    return self.smProxy.search_movie_parser.parse(cont, results=results)['data']
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\parser\http\utils.py", line 434, in parse
    data = self.parse_dom(dom)
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\parser\http\utils.py", line 526, in parse_dom
    return Rules(self.rules).extract(dom)
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\parser\http\piculet.py", line 373, in extract
    value = self.apply(element)
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\parser\http\piculet.py", line 517, in apply
    extracted = rule.extract(subroot)
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\parser\http\piculet.py", line 589, in extract
    list(map(self.extractor.transform, values))
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\parser\http\searchMovieParser.py", line 64, in <lambda>
    analyze_title(x.get('info', '')),
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\utils.py", line 327, in analyze_title
    series_d = analyze_title(series_title, canonical=canonicalSeries)
  File "C:\Users\kolt3\AppData\Roaming\Python\Python310\site-packages\imdb\utils.py", line 432, in analyze_title
    raise IMDbParserError('invalid title: "%s"' % original_t)

**Comment by LostRager** [comment]
Issue was fixed by forcing cinemagoer to update directly from their github. 

`pip install git+https://github.com/cinemagoer/cinemagoer`
